# Generated by Django 2.2.3 on 2019-08-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190817_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lose',
            new_name='loss',
        ),
    ]
