# Generated by Django 2.2.3 on 2019-08-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190817_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win',
        ),
    ]
