# Generated by Django 2.2.3 on 2019-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190817_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=120),
        ),
    ]
