# Generated by Django 2.2.3 on 2019-08-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190820_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
